### ISSUE TITLE
Content reorganization tracking issue

### ISSUE THREAD

**Issue by apoelstra** [roconnor-blockstream/SSS32#22]
I'd like to start working on bringing all the pieces together into a booklet format, but the required changes are fairly invasive (especially when renumbering pages). So this issue is a proposed process that I can follow and hopefully avoid stepping on toes:

1. [ ] Add title page; drop assembly instructions from license page (but probably keep the "require materials" list)
2. [ ] Add like 20 blank pages, after the license page and before everything else
3. [ ] Drop the existing "Constructing shares" page, it will be reconstructed
4. [ ] Add table of contents page & limited streaming parser; add outline of main contents (all the section headings but none of the main body)
5. [ ] Add "real" streaming parser and one page of material to demo it
6. [ ] Add remaining pages of material, at least enough to fill out the existing set of blanks; reinstate "Constructing shares" tables and other tables
7. [ ] Move volvelles and slide charts into "Module 0"
